### ISSUE TITLE
Error when intmax tx _mint_ ..

### ISSUE THREAD

**Issue by tenuki** [InternetMaximalism/intmax-rollup-cli#53]
Following the readme.md steps: 

```
$ intmax tx mint --amount 10 -i 0x00 
deposit successfully
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: unexpected response from /block/approve: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
', /home/user/Personal/intmax/intmax-rollup-cli/src/controller/mod.rs:922:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

* intmax:

```
~/Personal/intmax/intmax-rollup-cli$ intmax -V
intmax 2.2.1-alpha

~/Personal/intmax/intmax-rollup-cli$ cat ~/.intmax/config 
{"aggregator_url":"https://alpha.testnet.intmax.io/"}
```

* git log

```
$ git log
commit 012052e4114d71c647073e19966fed4e60842f38 (HEAD -> staging, tag: v2.2.1-alpha, origin/staging)
Author: Kc <20158457+hrmk1o3@users.noreply.github.com>
Date:   Fri Sep 8 11:06:51 2023 +0100

    resolve unapproval blocks (#51)
[..]
```

* sysinfo:

```
~/Personal/intmax/intmax-rollup-cli$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.2
Release:	21.2
Codename:	victoria

~/Personal/intmax/intmax-rollup-cli$ uname -v
#102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024
```

### Intermediate backtrace: 

```
$ RUST_BACKTRACE=1 intmax tx mint --amount 10 -i 0x00 
deposit successfully
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: unexpected response from /block/approve: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>


Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: intmax::controller::invoke_command::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   8: tokio::runtime::runtime::Runtime::block_on
   9: intmax::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/ops/function.rs:606:13
  13: std::panicking::try::do_call
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:483:40
  14: std::panicking::try
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:447:19
  15: std::panic::catch_unwind
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panic.rs:137:14
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/rt.rs:148:48
  17: std::panicking::try::do_call
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:483:40
  18: std::panicking::try
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:447:19
  19: std::panic::catch_unwind
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panic.rs:137:14
  20: std::rt::lang_start_internal
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/rt.rs:148:20
  21: main
  22: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  24: _start', /home/aweil/Personal/intmax/intmax-rollup-cli/src/controller/mod.rs:922:65
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
   4: intmax::controller::invoke_command::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   8: tokio::runtime::runtime::Runtime::block_on
   9: intmax::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### full backtrace

```
$ RUST_BACKTRACE=full intmax tx mint --amount 10 -i 0x00 
deposit successfully
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: unexpected response from /block/approve: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>


Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: intmax::controller::invoke_command::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   8: tokio::runtime::runtime::Runtime::block_on
   9: intmax::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/ops/function.rs:606:13
  13: std::panicking::try::do_call
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:483:40
  14: std::panicking::try
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:447:19
  15: std::panic::catch_unwind
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panic.rs:137:14
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/rt.rs:148:48
  17: std::panicking::try::do_call
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:483:40
  18: std::panicking::try
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:447:19
  19: std::panic::catch_unwind
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panic.rs:137:14
  20: std::rt::lang_start_internal
             at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/rt.rs:148:20
  21: main
  22: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  24: _start', /home/aweil/Personal/intmax/intmax-rollup-cli/src/controller/mod.rs:922:65
stack backtrace:
   0:     0x5581fb94fc30 - std::backtrace_rs::backtrace::libunwind::trace::hf6d6ec7fb2a9f0bf
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5581fb94fc30 - std::backtrace_rs::backtrace::trace_unsynchronized::hfd1a36a53305c28b
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5581fb94fc30 - std::sys_common::backtrace::_print_fmt::h72e336d500c35f75
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5581fb94fc30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6f7ff3379d918948
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5581fb9712be - core::fmt::write::h3afa65668df6f55a
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/fmt/mod.rs:1208:17
   5:     0x5581fb94a695 - std::io::Write::write_fmt::h7382492158d29038
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/io/mod.rs:1682:15
   6:     0x5581fb94f9f5 - std::sys_common::backtrace::_print::h946e0c8633f9c803
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5581fb94f9f5 - std::sys_common::backtrace::print::hd6913daf34dac590
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5581fb95125f - std::panicking::default_hook::{{closure}}::hffbe4fd1fe7c3e3b
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:267:22
   9:     0x5581fb950f9a - std::panicking::default_hook::h34712d52926a4a55
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:286:9
  10:     0x5581fb95195c - std::panicking::rust_panic_with_hook::h2b1dd2899955f83e
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:688:13
  11:     0x5581fb9516f7 - std::panicking::begin_panic_handler::{{closure}}::h8e2a4871c56530a6
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:579:13
  12:     0x5581fb9500dc - std::sys_common::backtrace::__rust_end_short_backtrace::h5dabfdb8d1388f1f
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x5581fb951412 - rust_begin_unwind
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:575:5
  14:     0x5581fb3879a3 - core::panicking::panic_fmt::h50d38f71cc566a11
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/panicking.rs:65:14
  15:     0x5581fb387c63 - core::result::unwrap_failed::ha112bd852a781407
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/result.rs:1791:5
  16:     0x5581fb4f12b6 - core::result::Result<T,E>::unwrap::h7372f0d058347c37
  17:     0x5581fb504e84 - intmax::controller::invoke_command::{{closure}}::hec39d7226a11a541
  18:     0x5581fb5261fb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3a867cc06085a019
  19:     0x5581fb4f45f6 - tokio::runtime::park::CachedParkThread::block_on::hb852d350f23c912c
  20:     0x5581fb3d41a0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hed1aa783da09d571
  21:     0x5581fb40558d - tokio::runtime::runtime::Runtime::block_on::h04d55616b010eb38
  22:     0x5581fb465731 - intmax::main::h3aa81e5e3108e214
  23:     0x5581fb3fc633 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5dfbb7958aeff177
  24:     0x5581fb4106a9 - std::rt::lang_start::{{closure}}::h10053639f1881237
  25:     0x5581fb94497b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h15ddbf90b732db0b
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/core/src/ops/function.rs:606:13
  26:     0x5581fb94497b - std::panicking::try::do_call::hd67a904821eb7b2d
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:483:40
  27:     0x5581fb94497b - std::panicking::try::hfec4a80d475e966c
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:447:19
  28:     0x5581fb94497b - std::panic::catch_unwind::h7bd3bd134c65ceab
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panic.rs:137:14
  29:     0x5581fb94497b - std::rt::lang_start_internal::{{closure}}::hea069f2da23b3c02
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/rt.rs:148:48
  30:     0x5581fb94497b - std::panicking::try::do_call::h8140d2c5d0fa34d6
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:483:40
  31:     0x5581fb94497b - std::panicking::try::h444993acbd0c0629
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panicking.rs:447:19
  32:     0x5581fb94497b - std::panic::catch_unwind::ha4fa5098eff5530c
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/panic.rs:137:14
  33:     0x5581fb94497b - std::rt::lang_start_internal::h33bb8f2385eabf94
                               at /rustc/e9493d63c2a57b91556dccd219e21821432c7445/library/std/src/rt.rs:148:20
  34:     0x5581fb465815 - main
  35:     0x7f282b77bd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x7f282b77be40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  37:     0x5581fb387e45 - _start
  38:                0x0 - <unknown>
```

**Comment by tenuki** [comment]
Now it started to return the same error when for example I ran: `intmax account add --nickname bob` .

Checking the connection to the aggregator I see client sending a kind of empty request:

```
GET / HTTP/1.1
accept: */*
host: alpha.testnet.intmax.io

HTTP/1.1 200 OK
Content-Length: 43
content-type: application/json
access-control-allow-credentials: true
access-control-expose-headers: content-type
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
date: Thu, 08 Feb 2024 11:50:45 GMT
Via: 1.1 google

{"name":"intmax-rollup","version":"v0.5.1"}
```

PS: I've switched the node connection to http from https, for easier network capture..

**Comment by tenuki** [comment]
Now it started to return the same error when for example I ran: `intmax account add --nickname bob` .

Checking the connection to the aggregator I see client sending a kind of empty request:

```
POST /block/approve HTTP/1.1
content-type: application/json
accept: */*
host: alpha.testnet.intmax.io
content-length: 2

{}

HTTP/1.1 502 Bad Gateway
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 332
Date: Thu, 08 Feb 2024 12:16:18 GMT


<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

PS: I've switched the node connection to http from https, for easier network capture..
